# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
   branches:
     include:
     - master
     - greenkeeper/*

# 
# pool:
#   vmImage: 'Ubuntu-16.04'
# 
# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'
# 
# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'
# 

jobs:
  - job: Windows
    strategy:
      matrix:
        Code30:
          CODE_VERSION: '1.30.0'
        Code40:
          CODE_VERSION: '1.40.0'
        CodeCurrent:
          CODE_VERSION:
        CodeInssiders:
          CODE_VERSION: 'insiders'
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - bash: sed -i.bak 's/"\*"//g' package.json
        displayName: 'Enable full coverage'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run test --silent'
  - job: macOS
    strategy:
      matrix:
        Code30:
          CODE_VERSION: '1.30.0'
        Code40:
          CODE_VERSION: '1.40.0'
        CodeCurrent:
          CODE_VERSION: 
        CodeInssiders:
          CODE_VERSION: 'insiders'
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - bash: sed -i.bak 's/"\*"//g' package.json
        displayName: 'Enable full coverage'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run test --silent'
  - job: Linux
    strategy:
      matrix:
        Code30:
          CODE_VERSION: '1.30.0'
        Code40:
          CODE_VERSION: '1.40.0'
        CodeCurrent:
          CODE_VERSION:
        CodeInssiders:
          CODE_VERSION: 'insiders'
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - bash: sed -i.bak 's/"\*"//g' package.json
        displayName: 'Enable full coverage'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run test --silent'
        env:
          DISPLAY: :10
  - job: Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    #condition: succeeded()
    dependsOn:
    - Windows
    - macOS
    - Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - task: Npm@1
        displayName: 'Run semantic-release'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run semantic-release --allow-same-version'
        env:
          VSCE_TOKEN: $(vsceToken)
          GH_TOKEN: $(githubToken)
          NPM_TOKEN: $(npmToken)
          GIT_AUTHOR_EMAIL: $(gitEmail)
          GIT_COMMITTER_EMAIL: $(gitEmail)
          GIT_AUTHOR_NAME: $(gitName)
          GIT_COMMITTER_NAME: $(gitName)
